spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect



#Prueba

#spring.datasource.url=jdbc:mysql://localhost:3306/backendjp?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=




#Producci\u00f3n
spring.datasource.url=jdbc:mysql://uykrzkrelcleyqee:ysLFKVjraeiRYnmLnOSA@bphd9pjqenesrmi3hfp7-mysql.services.clever-cloud.com:3306/bphd9pjqenesrmi3hfp7
spring.datasource.username=uykrzkrelcleyqee
spring.datasource.password=ysLFKVjraeiRYnmLnOSA





#JWT
jwt.secret = secret
jwt.expiration = 3600